CC = g++ -std=c++17
CLIENTE = cliente
CLASES_SERVIDOR = clases/Tablero/Tablero.h clases/Barco/Barco.h clases/Comun.h clases/Conexiones/ConexionServidor.h
CLASES_CLIENTE = clases/Conexiones/ConexionCliente.h  clases/Comun.h

#all:

$(SERVIDOR): $(SERVIDOR).cpp $(CLASES_SERVIDOR) 
	$(CC) servidor.cpp -o servidor -fopenmp 

$(CLIENTE): $(CLIENTE).cpp $(CLASES_CLIENTE) 
	$(CC) -o $(CLIENTE) $(CLIENTE).cpp   
 
#clean: